name: "cloud189_checkin"

on:
  schedule:
    # UTC 16点30分(北京时间 0点30分) 30 16 * * *
    - cron: "55 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: cloud189

    steps:
      - name: Checkout main 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-120 -n 1)

      - name: Install dependencies
        run: |
          npm install

      - name: Run main
        env:
          # pushplus
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          # cloud189
          CLOUD189_USERNAME_0: ${{secrets.CLOUD189_USERNAME_0}}
          CLOUD189_PASSWORD_0: ${{secrets.CLOUD189_PASSWORD_0}}
          CLOUD189_USERNAME_1: ${{secrets.CLOUD189_USERNAME_1}}
          CLOUD189_PASSWORD_1: ${{secrets.CLOUD189_PASSWORD_1}}
          CLOUD189_USERNAME_2: ${{secrets.CLOUD189_USERNAME_2}}
          CLOUD189_PASSWORD_2: ${{secrets.CLOUD189_PASSWORD_2}}
          CLOUD189_USERNAME_3: ${{secrets.CLOUD189_USERNAME_3}}
          CLOUD189_PASSWORD_3: ${{secrets.CLOUD189_PASSWORD_3}}
          CLOUD189_USERNAME_4: ${{secrets.CLOUD189_USERNAME_4}}
          CLOUD189_PASSWORD_4: ${{secrets.CLOUD189_PASSWORD_4}}

        run: |
          node ./task/cloud189_checkin.js

      - name: Delete old workflow run using Github Token
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: "cloud189_checkin"
