name: "glados_chenkin"

on:
  schedule:
    # UTC 16点30分(北京时间 0点30分) 30 16 * * *
    - cron: "35 16 * * *"
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-120 -n 1)

      - name: Install dependencies
        run: |
          npm install

      - name: Run js
        env:
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          node ./task/glados_chenkin.js
