name: "hifiti_checkin"

on:
  schedule:
    # UTC 16点30分(北京时间 0点30分) 30 16 * * *
    - cron: "40 16 * * *"
  workflow_dispatch:

env:
  IS_SCHEDULE: ${{ github.event_name  == 'schedule' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: hifiti

    steps:
      - name: Checkout main 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # - name: apt-get Install 
      #   run: |
      #     sudo apt-get upgrade
      #     sudo apt-get update
      #     sudo apt-get install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
          
      #     sudo apt-get install -y libgbm-dev
      #     sudo apt-get install libglib2.0-0

      # - name: Install chromium-browser
      #   run: |
      #     sudo apt-get install chromium-browser
          
      # - name: which chromium-browser
      #   run: |
      #     which chromium-browser
          
      - name: Install dependencies
        run: |
          npm install

      - name: Install dependencies puppeteer
        run: |
          npm install puppeteer
          
      - name: Run main
        env:
          # wxpusher
          WXPUSHER_TOKEN: ${{ secrets.WXPUSHER_TOKEN }}
          WXPUSHER_UID: ${{ secrets.WXPUSHER_UID }}
          
          # # pushplus
          # PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          
          # HIFITI
          HIFITI_EMAIL_0: ${{ secrets.HIFITI_EMAIL_0 }}
          HIFITI_PASSWORD_0: ${{ secrets.HIFITI_PASSWORD_0 }}
          HIFITI_COOKIE_0: ${{ secrets.HIFITI_COOKIE_0 }}
          
          HIFITI_EMAIL_1: ${{ secrets.HIFITI_EMAIL_1 }}
          HIFITI_PASSWORD_1: ${{ secrets.HIFITI_PASSWORD_1 }}
          HIFITI_COOKIE_1: ${{ secrets.HIFITI_COOKIE_1 }}
          
          # 在 Action 中运行时更新 Repository secrets
          GP_TOKEN: ${{ secrets.GP_TOKEN }}
        run: |
          node ./task/hifiti_checkin.js

      - name: Delete old workflow run using Github Token
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: "hifiti_checkin"
