name: "ikuuu_checkin"

on:
  schedule:
    # UTC 16点30分(北京时间 0点30分) 30 16 * * *
    - cron: "45 16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ikuuu

    steps:
      - name: Checkout main 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-120 -n 1)

      - name: Install dependencies
        run: |
          npm install

      - name: Run main
        env:
          IKUUU_USER: ${{ secrets.IKUUU_USER }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          IKUUU_EMAIL_0: ${{secrets.IKUUU_EMAIL_0}}
          IKUUU_PASSWD_0: ${{secrets.IKUUU_PASSWD_0}}
          IKUUU_EMAIL_1: ${{secrets.IKUUU_EMAIL_1}}
          IKUUU_PASSWD_1: ${{secrets.IKUUU_PASSWD_1}}
          IKUUU_EMAIL_2: ${{secrets.IKUUU_EMAIL_2}}
          IKUUU_PASSWD_2: ${{secrets.IKUUU_PASSWD_2}}
          IKUUU_EMAIL_3: ${{secrets.IKUUU_EMAIL_3}}
          IKUUU_PASSWD_3: ${{secrets.IKUUU_PASSWD_3}}
          IKUUU_EMAIL_4: ${{secrets.IKUUU_EMAIL_4}}
          IKUUU_PASSWD_4: ${{secrets.IKUUU_PASSWD_4}}
        run: |
          node ./task/ikuuu_checkin.js

      - name: Delete old workflow run using Github Token
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: "ikuuu_checkin"
