name: "v2free_checkin"

on:
  schedule:
    # UTC 16点30分(北京时间 0点30分) 30 16 * * *
    - cron: "50 16 * * *"
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main 
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-120 -n 1)

      - name: Install dependencies
        run: |
          npm install

      - name: Run main
        env:
          V2FREE_USER: ${{ secrets.V2FREE_USER }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          node ./task/v2free_checkin.js

      - name: Delete old workflow run using Github Token
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: "v2free_checkin"
